export const FIELD_LABELS = {
    LOT_NO :"Lot No",
    BREAK : "Break",
    ESTATE_CODE: "Estate Code",
    ESTATE_NUMBER : "Estate Number",
    ESTATE_NAME: "Estate Name",
    STORE_ADDRESS: "Store Address",
    ELEVATION: "Elevation",
    NO_OF_DELIVERY_DAYS: "No of Delivery Days",
    REMARKS: "Remarks",
    BOX_NUMBER: "Box Number",
    GRADE: "Grade",
    STANDARD: "Standard",
    CHEST_TYPE: "Chest Type",
    SACK_TYPE: "Sacks Type",
    MAIN_BUYER: "Main Buyer",
    SAMPLES_RECEIVED: "Samples Received",
    ITEM_CODE: "Item Code",
    ITEM_NAME:"Item Description",
    DESCRIPTION: "Description",
    STATUS: "Status",
    NO_OF_BAGS: "No of Bags",
    WEIGHT_OF_BAG: "Weight of Bag",
    PO_NUMBER: "PO Number",
    TOTAL_QUANTITY: "Total Quantity",
    ALLOWANCE: "Allowance",
    PRICE: "Price",
    VALUE: "Value",
    POSTING_DATE: "Posting Date",
    INVOICE_NUMBER: 'Invoice Number',
    SALES_CODE: 'Sales Code',
    NET_QUANTITY: 'Net Quantity',
    CONTRACT_NO: 'Contract No',
    PAYMENT: 'Payment Type'
}
